/**
 * Regenerate src/web/fonts.ts from the site's self-hosted fonts (site/src/assets/fonts, the
 * Fontsource latin subsets with their OFL texts beside them). The dashboard image has no asset
 * directory and serves nothing from disk (#43, ADR D11), so it carries the same three files as
 * base64 constants, each with the SHA-256 of its bytes. Run it after changing a font there:
 *
 *   bun --no-env-file scripts/web-fonts.ts
 *
 * tests/unit/web-parity.test.ts fails while the generated file and the site's fonts differ.
 */
import { createHash } from "node:crypto";

/** The site's fonts, in the order the generated file lists them; the stem is the file name. */
const FONTS = [
  { name: "SORA", stem: "sora-latin-wght-normal" },
  { name: "MANROPE", stem: "manrope-latin-wght-normal" },
  { name: "JETBRAINS_MONO", stem: "jetbrains-mono-latin-wght-normal" },
] as const;

/** The site directory the fonts are read from, as the generated header names it. */
const SOURCE = "site/src/assets/fonts";
/** Every WOFF2 file starts with these four bytes. */
const WOFF2_MAGIC = "wOF2";

const constants: string[] = [];
for (const { name, stem } of FONTS) {
  const bytes = new Uint8Array(
    await Bun.file(new URL(`../${SOURCE}/${stem}.woff2`, import.meta.url)).arrayBuffer(),
  );
  // A renamed or truncated file must fail here, not as a font the browser silently drops: a WOFF2
  // header opens with the magic and records the file's total length at bytes 8-11 (big-endian).
  if (new TextDecoder().decode(bytes.subarray(0, 4)) !== WOFF2_MAGIC)
    throw new Error(`${SOURCE}/${stem}.woff2 is not a WOFF2 file.`);
  if (
    bytes.byteLength < 12 ||
    new DataView(bytes.buffer, bytes.byteOffset).getUint32(8) !== bytes.byteLength
  )
    throw new Error(
      `${SOURCE}/${stem}.woff2 is not as long as its header says: truncated or padded.`,
    );
  const sha256 = createHash("sha256").update(bytes).digest("hex");
  // Laid out the way Biome formats it, so a regenerated file needs no formatting pass.
  constants.push(
    `/** ${SOURCE}/${stem}.woff2, ${bytes.byteLength} bytes. */\n` +
      `export const ${name}: FontFile = {\n` +
      `  stem: "${stem}",\n` +
      `  sha256: "${sha256}",\n` +
      `  base64:\n    "${bytes.toBase64()}",\n` +
      "};\n",
  );
}

const header = `/**
 * GENERATED by scripts/web-fonts.ts from ${SOURCE}/*.woff2; do not edit. Regenerate with
 * \`bun --no-env-file scripts/web-fonts.ts\` after changing a font there.
 *
 * The dashboard's self-hosted fonts as base64 constants, so the image needs no asset directory
 * (#43, ADR D11). assets.ts decodes and serves each at a hashed path. Sora, Manrope and
 * JetBrains Mono are under the SIL Open Font License 1.1; their notices are in notices.ts.
 */

/** One font file, as the site ships it. */
export interface FontFile {
  /** The site file's name without ".woff2", served as /assets/<stem>.<hash>.woff2. */
  readonly stem: string;
  /** The SHA-256 of the file's bytes, in hex. */
  readonly sha256: string;
  /** The file's bytes in base64. */
  readonly base64: string;
}
`;

const target = new URL("../src/web/fonts.ts", import.meta.url);
await Bun.write(target, [header, ...constants].join("\n"));
console.log(`Wrote src/web/fonts.ts from ${FONTS.length} fonts in ${SOURCE}.`);
